---
title: "MT5763_2_200028225 -- CHANGE"
subtitle: "MT5763 : Individual courserwork 2" 
author: "Student ID number : 200028225"
date: October 28, 2020
output: pdf_document
---

Git Hub Link: [link to my github repository](https://github.com/Kinjalpatel-00/MT5763_2_200028225.git)

\newpage

## Abstract

## Introduction
add purpose of your investigation 

## Analysis Description -
#### clear account of what you did statistically as well as the data
#### wrangling,) and why

created the copy of existing dataset
there was no null values in dataset. havet needed to removed any row or columns
not needed to change the name of columns. 

DATA WRAGLING:
COPIED EXISTING DATA TO DATA SET TO AVOID MUNIPLATION ON ORIGINAL DATASET
TRANSFORMING WIDE DATA TO LONG DATA - created 4 dataset and combined them
convered hair growth values inches to mm.



## Results
#### add visualization 
#### are the results clearly explained and presented (includes data visualization):
Draw table of mean and different values to answers each of queation.
NUMERICA SUMMARY TO CHECK MEAN , AND OTHER VALUES.
HISTOGRAM OF AGE VARIABLE TO SEE IN WHICH AGE PPL ARE DOING WHICH TRAETAREMENT MORE.
frequency table to check data set has which age highest data based on age
summary of new data set 

## Further research - 

## Conclusion


## References

## Appendices - SAS Code

Code can be reproducible by changeing file location. 

```
/* Generated Code (IMPORT) */
/* Source File: Baldy.csv */
/* Source Path: /folders/myfolders/MT5763_2_200028225 */
/* Code generated on: 10/22/20, 4:48 PM */

%web_drop_table(DATA.BALDY);

FILENAME REFFILE '/folders/myfolders/Baldy.csv';

PROC IMPORT DATAFILE=REFFILE
	DBMS=CSV
	OUT=DATA.BALDY;
	GETNAMES=YES;
RUN;

/* View the basic details of dataset */
PROC CONTENTS DATA=DATA.BALDY; 
RUN;

/* Disply the dataset in table format */
%web_open_table(DATA.BALDY);


/* Creating the copy of existing dataset*/
DATA DATA.COPY_DATASET;
SET DATA.BALDY;
RUN;

/*----------------------- SUMMIRINZING DATASET --------------------------------*/

/* Summirizing the numeric variables of different treatments*/
PROC UNIVARIATE DATA= DATA.COPY_DATASET;
VAR LUXURIANT PLACEBO BALDBEGONE SKINHEADNOMORE;
RUN;


/* Summirizing the numeric variables of age when treatment was done*/
PROC UNIVARIATE DATA= DATA.COPY_DATASET;
VAR AGELUXURIANT AGEPLACEBO AGEBALDBEGONE AGESKINHEADNOMORE;
RUN;




/*---------------- CONVERTING THE DATASET TO THREE COLUMNS AGE, HAIR GROWTH VALUE, TREATMENT*/

/* CHANGE DATASET TRANSPOSE WIDE TO LONG  */

DATA DATA.DATA_LUXURIANT; 
	SET DATA.COPY_DATASET ;
	Treatment = "Luxuriant";
	RENAME AgeLuxuriant = Age;
	RENAME LUXURIANT = HairGrowthValue;
	KEEP AgeLuxuriant LUXURIANT Treatment;
RUN;

DATA DATA.DATA_PLACEBO; 
	SET DATA.COPY_DATASET ;
	Treatment = "Placebo";
	RENAME AGEPLACEBO = Age;
	RENAME PLACEBO = HairGrowthValue;
	KEEP AGEPLACEBO PLACEBO Treatment; 
RUN;

DATA DATA.DATA_BALDBEGONE; 
	SET DATA.COPY_DATASET ;
	Treatment = "BaldBeGone";
	RENAME AGEBALDBEGONE = Age;
	RENAME BALDBEGONE = HairGrowthValue;
	KEEP AGEBALDBEGONE BALDBEGONE Treatment; 
RUN;

DATA DATA.DATA_SKINHEADNOMORE; 
	SET DATA.COPY_DATASET ;
	Treatment = "SkinheadNoMore";
	RENAME AGESKINHEADNOMORE = Age;
	RENAME SKINHEADNOMORE = HairGrowthValue;
	KEEP AGESKINHEADNOMORE SKINHEADNOMORE Treatment; 
RUN;

/* Merging all 4 datasets*/
DATA DATA.TIDY_DATASET;
    SET DATA.DATA_LUXURIANT DATA.DATA_PLACEBO DATA.DATA_BALDBEGONE DATA.DATA_SKINHEADNOMORE ;
RUN;


/* CHANGE HAIR GROTH VALUES(INCHES) TO MILIMIITER*/
DATA DATA.TIDY_DATASET;
	SET DATA.TIDY_DATASET;
	HairGrowthValue = HairGrowthValue * 25.4;
RUN;


/* FREQUENCY TABLES for summery */
PROC FREQ DATA=DATA.TIDY_DATASET;
    TABLE Age ;
RUN;

/* summerizing tidy dataset */
PROC CONTENTS DATA=DATA.TIDY_DATASET; 
RUN;

PROC UNIVARIATE DATA= DATA.TIDY_DATASET;
VAR Age HairGrowthValue;
RUN;



/* ------------- Question 1 ------------- */

DATA DATA.DATA_q1; 
	SET DATA.TIDY_DATASET;
	WHERE Treatment = "Luxuriant" OR Treatment = "Placebo";
RUN;

PROC UNIVARIATE DATA= DATA.DATA_q1;
VAR AGE HAIRGROWTHVALUE;
RUN;

proc template;
define statgraph sgdesign;
dynamic _AGE _HAIRGROWTHVALUE _TREATMENT _TREATMENT2;
begingraph;
   entrytitle halign=center 'Graph: 1 Effect of luxuriant treatment over the placbo treatment';
   layout lattice / rowdatarange=data columndatarange=data rowgutter=10 columngutter=10;
      layout overlay;
         seriesplot x=_AGE y=_HAIRGROWTHVALUE / group=_TREATMENT curvelabel=_TREATMENT2 name='series' connectorder=xaxis;
      endlayout;
   endlayout;
endgraph;
end;
run;

proc sgrender data=DATA.DATA_q1 template=sgdesign;
dynamic _AGE="AGE" _HAIRGROWTHVALUE="HAIRGROWTHVALUE" _TREATMENT="TREATMENT" _TREATMENT2="TREATMENT";
run;

/* ------------- Question 2 ------------- */
proc template;
define statgraph sgdesign;
dynamic _HAIRGROWTHVALUE _TREATMENT _TREATMENT2;
begingraph;
  entrytitle halign=center 'Graph: 1 Effect of luxuriant treatment over the placbo treatment';
   entryfootnote halign=left 'Type in your footnote...';
   layout lattice / rowdatarange=data columndatarange=data rowgutter=10 columngutter=10;
      layout overlay / xaxisopts=( discreteopts=( tickvaluefitpolicy=splitrotate));
         boxplot x=_TREATMENT y=_HAIRGROWTHVALUE / group=_TREATMENT2 name='box' groupdisplay=Cluster;
      endlayout;
   endlayout;
endgraph;
end;
run;

proc sgrender data=DATA.TIDY_DATASET template=sgdesign;
dynamic _HAIRGROWTHVALUE="HAIRGROWTHVALUE" _TREATMENT="TREATMENT" _TREATMENT2="TREATMENT";
run;



```
